version: "3.8"
services:
  
  ## Go Simple Web Service API
  ## ========================
  ## web:
  ##  build: .
  ##  ports:
  ##    - "3000:3000"
  ##  depends_on:
  ##    - db
  
  ## Postgres Database
  ## ========================
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secr3tPWD
      POSTGRES_DB: web_db
    volumes:
      - ./migrations:/docker-entrypoint-initdb.d
    ports:
      - "5433:5432"

  ## pgAdmin
  ## ========================
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@demo.com
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_LISTEN_ADDRESS: 0.0.0.0
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "5050:80"
    links:
      - db:pgsql-server
    depends_on:
      - db

  ## Swagger UI - REST API Documentation Tool
  ## ========================================
  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: swagger_ui_container
    ports:
      - "8090:8080"
    volumes:
      - ./doc:/usr/share/nginx/html/doc
    environment:
      URLS: "[{ url: 'doc/articles.yml', name: 'Articles'}]"
    #depends_on:
    #  - web