version: "3.8"
services:
  
  ## Go Simple Web Service API
  ## ========================
  web:
    build: .
    ports:
      - "8999:8999"
    depends_on:
      - db
      - redis
  
  ## Postgres Database
  ## ========================
  db:
    image: postgres:latest
    container_name: pgsql-server
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secr3tPWD
      POSTGRES_DB: web_db
    volumes:
      - ./migrations:/docker-entrypoint-initdb.d
    ##ports:
    ##  - "5433:5432"

  ## Redis
  ## ========================
  redis:
    image: "bitnami/redis:latest"
    container_name: redis-server
    ##ports:
    ##  - 6379:6379
    environment:
      - REDIS_REPLICATION_MODE=master
      - REDIS_PASSWORD=my_master_password

  ## pgAdmin
  ## ========================
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@demo.com
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_LISTEN_ADDRESS: 0.0.0.0
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "5050:80"
    links:
      - db:pgsql-server
    depends_on:
      - db

  ## Swagger UI - REST API Documentation Tool
  ## ========================================
  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: swagger_ui_container
    ports:
      - "8090:8080"
    volumes:
      - ./doc:/usr/share/nginx/html/doc
    environment:
      URLS: "[{ url: 'doc/articles.yml', name: 'Articles'}]"
    depends_on:
      - web

  ## Extra
  ## Grafana, Promether, Redis Exporter
  grafana:
    image: grafana/grafana
    ports:
      - 3210:3000

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      
  redis-exporter:
    image: oliver006/redis_exporter
    ports:
      - 9121:9121
    restart: unless-stopped
    environment:
      REDIS_ADDR: "redis:6379"
      REDIS_USER: null
      REDIS_PASSWORD: my_master_password
    links:
      - redis
      - prometheus